import chromadb
from sentence_transformers import SentenceTransformer

problems = [
    {"title": "Two Sum", "difficulty": "Easy", "tags": "HashMap", "companies": "Google,Amazon"},
    {"title": "Add Two Numbers", "difficulty": "Medium", "tags": "Linked List", "companies": "Google,Amazon,Meta"},
    {"title": "Longest Substring Without Repeating Characters", "difficulty": "Medium", "tags": "Sliding Window", "companies": "Google,Meta"},
    {"title": "Median of Two Sorted Arrays", "difficulty": "Hard", "tags": "Binary Search", "companies": "Google,Amazon"},
    {"title": "Longest Palindromic Substring", "difficulty": "Medium", "tags": "Dynamic Programming", "companies": "Amazon,Meta"},
    {"title": "Zigzag Conversion", "difficulty": "Medium", "tags": "String", "companies": "Amazon"},
    {"title": "Reverse Integer", "difficulty": "Medium", "tags": "Math", "companies": "Google,Amazon"},
    {"title": "String to Integer atoi", "difficulty": "Medium", "tags": "String,Math", "companies": "Amazon"},
    {"title": "Palindrome Number", "difficulty": "Easy", "tags": "Math", "companies": "Google"},
    {"title": "Regular Expression Matching", "difficulty": "Hard", "tags": "Dynamic Programming", "companies": "Google,Meta"},
    {"title": "Container With Most Water", "difficulty": "Medium", "tags": "Two Pointers", "companies": "Google,Amazon"},
    {"title": "Integer to Roman", "difficulty": "Medium", "tags": "Math,String", "companies": "Google,Amazon"},
    {"title": "Roman to Integer", "difficulty": "Easy", "tags": "Math,String", "companies": "Google,Amazon"},
    {"title": "Longest Common Prefix", "difficulty": "Easy", "tags": "String,Trie", "companies": "Google,Amazon"},
    {"title": "3Sum", "difficulty": "Medium", "tags": "Two Pointers", "companies": "Google,Amazon,Meta"},
    {"title": "3Sum Closest", "difficulty": "Medium", "tags": "Two Pointers", "companies": "Google"},
    {"title": "Letter Combinations of a Phone Number", "difficulty": "Medium", "tags": "Backtracking", "companies": "Google,Amazon,Meta"},
    {"title": "4Sum", "difficulty": "Medium", "tags": "Two Pointers", "companies": "Google"},
    {"title": "Remove Nth Node From End of List", "difficulty": "Medium", "tags": "Linked List,Two Pointers", "companies": "Google,Amazon"},
    {"title": "Valid Parentheses", "difficulty": "Easy", "tags": "Stack", "companies": "Google,Microsoft"},
    {"title": "Merge Two Sorted Lists", "difficulty": "Easy", "tags": "Linked List", "companies": "Google,Amazon"},
    {"title": "Generate Parentheses", "difficulty": "Medium", "tags": "Backtracking", "companies": "Google,Amazon,Meta"},
    {"title": "Merge K Sorted Lists", "difficulty": "Hard", "tags": "Heap,Linked List", "companies": "Google,Amazon"},
    {"title": "Swap Nodes in Pairs", "difficulty": "Medium", "tags": "Linked List", "companies": "Google"},
    {"title": "Reverse Nodes in k-Group", "difficulty": "Hard", "tags": "Linked List", "companies": "Google,Amazon"},
    {"title": "Remove Duplicates from Sorted Array", "difficulty": "Easy", "tags": "Two Pointers", "companies": "Google,Amazon"},
    {"title": "Remove Element", "difficulty": "Easy", "tags": "Two Pointers", "companies": "Google"},
    {"title": "Implement strStr", "difficulty": "Easy", "tags": "String,KMP", "companies": "Google,Amazon"},
    {"title": "Divide Two Integers", "difficulty": "Medium", "tags": "Bit Manipulation,Math", "companies": "Google"},
    {"title": "Substring with Concatenation of All Words", "difficulty": "Hard", "tags": "Sliding Window,HashMap", "companies": "Google"},
    {"title": "Next Permutation", "difficulty": "Medium", "tags": "Array,Two Pointers", "companies": "Google"},
    {"title": "Longest Valid Parentheses", "difficulty": "Hard", "tags": "Stack,Dynamic Programming", "companies": "Google,Amazon"},
    {"title": "Search in Rotated Sorted Array", "difficulty": "Medium", "tags": "Binary Search", "companies": "Google"},
    {"title": "Find First and Last Position of Element", "difficulty": "Medium", "tags": "Binary Search", "companies": "Google,Amazon"},
    {"title": "Search Insert Position", "difficulty": "Easy", "tags": "Binary Search", "companies": "Google"},
    {"title": "Valid Sudoku", "difficulty": "Medium", "tags": "Array,HashMap", "companies": "Google,Amazon"},
    {"title": "Sudoku Solver", "difficulty": "Hard", "tags": "Backtracking", "companies": "Google"},
    {"title": "Count and Say", "difficulty": "Medium", "tags": "String", "companies": "Google"},
    {"title": "Combination Sum", "difficulty": "Medium", "tags": "Backtracking", "companies": "Google,Amazon"},
    {"title": "Combination Sum II", "difficulty": "Medium", "tags": "Backtracking", "companies": "Google"},
    {"title": "First Missing Positive", "difficulty": "Hard", "tags": "Array,HashMap", "companies": "Google,Amazon"},
    {"title": "Trapping Rain Water", "difficulty": "Hard", "tags": "Two Pointers,Stack", "companies": "Google,Amazon"},
    {"title": "Multiply Strings", "difficulty": "Medium", "tags": "String,Math", "companies": "Google"},
    {"title": "Wildcard Matching", "difficulty": "Hard", "tags": "Dynamic Programming", "companies": "Google"},
    {"title": "Jump Game II", "difficulty": "Medium", "tags": "Greedy", "companies": "Google,Amazon"},
    {"title": "Permutations", "difficulty": "Medium", "tags": "Backtracking", "companies": "Google,Amazon,Meta"},
    {"title": "Permutations II", "difficulty": "Medium", "tags": "Backtracking", "companies": "Google"},
    {"title": "Rotate Image", "difficulty": "Medium", "tags": "Matrix", "companies": "Google,Amazon,Meta"},
    {"title": "Group Anagrams", "difficulty": "Medium", "tags": "HashMap", "companies": "Google,Amazon,Meta"},
    {"title": "Pow(x, n)", "difficulty": "Medium", "tags": "Math,Recursion", "companies": "Google,Amazon"},
    {"title": "N-Queens", "difficulty": "Hard", "tags": "Backtracking", "companies": "Google"},
    {"title": "N-Queens II", "difficulty": "Hard", "tags": "Backtracking", "companies": "Google"},
    {"title": "Maximum Subarray", "difficulty": "Medium", "tags": "Dynamic Programming", "companies": "Amazon"},
    {"title": "Spiral Matrix", "difficulty": "Medium", "tags": "Matrix", "companies": "Google,Amazon,Meta"},
    {"title": "Jump Game", "difficulty": "Medium", "tags": "Greedy", "companies": "Google,Amazon"},
    {"title": "Merge Intervals", "difficulty": "Medium", "tags": "Sorting", "companies": "Google,Amazon"},
    {"title": "Insert Interval", "difficulty": "Medium", "tags": "Intervals", "companies": "Google,LinkedIn"},
    {"title": "Length of Last Word", "difficulty": "Easy", "tags": "String", "companies": "Google"},
    {"title": "Spiral Matrix II", "difficulty": "Medium", "tags": "Matrix", "companies": "Google"},
    {"title": "Permutation Sequence", "difficulty": "Hard", "tags": "Math,Backtracking", "companies": "Google"},
    {"title": "Rotate List", "difficulty": "Medium", "tags": "Linked List,Two Pointers", "companies": "Google"},
    {"title": "Unique Paths", "difficulty": "Medium", "tags": "Dynamic Programming", "companies": "Google,Amazon"},
    {"title": "Unique Paths II", "difficulty": "Medium", "tags": "Dynamic Programming", "companies": "Google"},
    {"title": "Minimum Path Sum", "difficulty": "Medium", "tags": "Dynamic Programming", "companies": "Google,Amazon"},
    {"title": "Valid Number", "difficulty": "Hard", "tags": "String,Math", "companies": "Google"},
    {"title": "Plus One", "difficulty": "Easy", "tags": "Array,Math", "companies": "Google,Amazon"},
    {"title": "Add Binary", "difficulty": "Easy", "tags": "String,Bit Manipulation", "companies": "Google,Amazon"},
    {"title": "Text Justification", "difficulty": "Hard", "tags": "String,Greedy", "companies": "Google"},
    {"title": "Sqrt(x)", "difficulty": "Easy", "tags": "Math,Binary Search", "companies": "Google,Amazon"},
    {"title": "Climbing Stairs", "difficulty": "Easy", "tags": "Dynamic Programming", "companies": "Google,Amazon"},
    {"title": "Simplify Path", "difficulty": "Medium", "tags": "Stack,String", "companies": "Google"},
    {"title": "Edit Distance", "difficulty": "Hard", "tags": "Dynamic Programming", "companies": "Google,Amazon"},
    {"title": "Set Matrix Zeroes", "difficulty": "Medium", "tags": "Matrix", "companies": "Google,Amazon"},
    {"title": "Search a 2D Matrix", "difficulty": "Medium", "tags": "Binary Search,Matrix", "companies": "Google,Amazon"},
    {"title": "Sort Colors", "difficulty": "Medium", "tags": "Array,Two Pointers", "companies": "Google,Amazon"},
    {"title": "Minimum Window Substring", "difficulty": "Hard", "tags": "Sliding Window", "companies": "Google,Meta"},
    {"title": "Subsets", "difficulty": "Medium", "tags": "Backtracking", "companies": "Google,Amazon,Meta"},
    {"title": "Word Search", "difficulty": "Medium", "tags": "DFS,Backtracking", "companies": "Google,Meta"},
    {"title": "Remove Duplicates from Sorted Array II", "difficulty": "Medium", "tags": "Two Pointers", "companies": "Google"},
    {"title": "Search in Rotated Sorted Array II", "difficulty": "Medium", "tags": "Binary Search", "companies": "Google"},
    {"title": "Remove Duplicates from Sorted List II", "difficulty": "Medium", "tags": "Linked List", "companies": "Google"},
    {"title": "Remove Duplicates from Sorted List", "difficulty": "Easy", "tags": "Linked List", "companies": "Google"},
    {"title": "Largest Rectangle in Histogram", "difficulty": "Hard", "tags": "Stack,Monotonic Stack", "companies": "Google,Amazon"},
    {"title": "Maximal Rectangle", "difficulty": "Hard", "tags": "Stack,Dynamic Programming", "companies": "Google,Amazon"},
    {"title": "Partition List", "difficulty": "Medium", "tags": "Linked List,Two Pointers", "companies": "Google"},
    {"title": "Scramble String", "difficulty": "Hard", "tags": "Dynamic Programming", "companies": "Google"},
    {"title": "Merge Sorted Array", "difficulty": "Easy", "tags": "Array,Two Pointers", "companies": "Google,Amazon"},
    {"title": "Gray Code", "difficulty": "Medium", "tags": "Bit Manipulation,Math", "companies": "Google"},
    {"title": "Subsets II", "difficulty": "Medium", "tags": "Backtracking", "companies": "Google"},
    {"title": "Decode Ways", "difficulty": "Medium", "tags": "Dynamic Programming", "companies": "Google,Amazon"},
    {"title": "Reverse Linked List II", "difficulty": "Medium", "tags": "Linked List", "companies": "Google"},
    {"title": "Restore IP Addresses", "difficulty": "Medium", "tags": "Backtracking,String", "companies": "Google"},
    {"title": "Binary Tree Inorder Traversal", "difficulty": "Easy", "tags": "Tree,DFS", "companies": "Google,Amazon"},
    {"title": "Unique Binary Search Trees II", "difficulty": "Medium", "tags": "Tree,Dynamic Programming", "companies": "Google"},
    {"title": "Unique Binary Search Trees", "difficulty": "Medium", "tags": "Dynamic Programming", "companies": "Google"},
    {"title": "Validate Binary Search Tree", "difficulty": "Medium", "tags": "Tree,DFS", "companies": "Google,Amazon"},
    {"title": "Recover Binary Search Tree", "difficulty": "Medium", "tags": "Tree,DFS", "companies": "Google"},
    {"title": "Same Tree", "difficulty": "Easy", "tags": "Tree,DFS", "companies": "Google"},
    {"title": "Symmetric Tree", "difficulty": "Easy", "tags": "Tree,BFS/DFS", "companies": "Google,Amazon"},
    {"title": "Binary Tree Level Order Traversal", "difficulty": "Medium", "tags": "BFS,Tree", "companies": "Google,Amazon"},
    {"title": "Binary Tree Zigzag Level Order Traversal", "difficulty": "Medium", "tags": "BFS,Tree", "companies": "Google,Amazon"},
    {"title": "Maximum Depth of Binary Tree", "difficulty": "Easy", "tags": "Tree,DFS", "companies": "Google,Amazon"},
    {"title": "Construct Binary Tree from Preorder and Inorder", "difficulty": "Medium", "tags": "Tree,DFS", "companies": "Google,Amazon"},
    {"title": "Construct Binary Tree from Inorder and Postorder", "difficulty": "Medium", "tags": "Tree,DFS", "companies": "Google"},
    {"title": "Binary Tree Level Order Traversal II", "difficulty": "Medium", "tags": "BFS,Tree", "companies": "Google"},
    {"title": "Convert Sorted Array to Binary Search Tree", "difficulty": "Easy", "tags": "Tree,Divide and Conquer", "companies": "Google,Amazon"},
    {"title": "Convert Sorted List to Binary Search Tree", "difficulty": "Medium", "tags": "Tree,Linked List", "companies": "Google"},
    {"title": "Balanced Binary Tree", "difficulty": "Easy", "tags": "Tree,DFS", "companies": "Google,Amazon"},
    {"title": "Minimum Depth of Binary Tree", "difficulty": "Easy", "tags": "Tree,BFS", "companies": "Google"},
    {"title": "Path Sum", "difficulty": "Easy", "tags": "Tree,DFS", "companies": "Google,Amazon"},
    {"title": "Path Sum II", "difficulty": "Medium", "tags": "Tree,DFS,Backtracking", "companies": "Google"},
    {"title": "Flatten Binary Tree to Linked List", "difficulty": "Medium", "tags": "Tree,DFS", "companies": "Google,Meta"},
    {"title": "Distinct Subsequences", "difficulty": "Hard", "tags": "Dynamic Programming", "companies": "Google"},
    {"title": "Populating Next Right Pointers in Each Node", "difficulty": "Medium", "tags": "Tree,BFS", "companies": "Google"},
    {"title": "Populating Next Right Pointers in Each Node II", "difficulty": "Medium", "tags": "Tree,BFS", "companies": "Google"},
    {"title": "Pascal Triangle", "difficulty": "Easy", "tags": "Dynamic Programming", "companies": "Google,Amazon"},
    {"title": "Pascal Triangle II", "difficulty": "Easy", "tags": "Dynamic Programming", "companies": "Google"},
    {"title": "Triangle", "difficulty": "Medium", "tags": "Dynamic Programming", "companies": "Google"},
    {"title": "Best Time to Buy and Sell Stock", "difficulty": "Easy", "tags": "Array,Dynamic Programming", "companies": "Amazon"},
    {"title": "Best Time to Buy and Sell Stock II", "difficulty": "Medium", "tags": "Greedy", "companies": "Amazon"},
    {"title": "Best Time to Buy and Sell Stock III", "difficulty": "Hard", "tags": "Dynamic Programming", "companies": "Google,Amazon"},
    {"title": "Binary Tree Maximum Path Sum", "difficulty": "Hard", "tags": "Tree,DFS", "companies": "Google,Amazon,Meta"},
    {"title": "Valid Palindrome", "difficulty": "Easy", "tags": "String,Two Pointers", "companies": "Google,Meta"},
    {"title": "Word Ladder II", "difficulty": "Hard", "tags": "BFS,Backtracking", "companies": "Google"},
    {"title": "Word Ladder", "difficulty": "Hard", "tags": "BFS,Graph", "companies": "Google"},
    {"title": "Longest Consecutive Sequence", "difficulty": "Medium", "tags": "HashMap", "companies": "Google,Amazon"},
    {"title": "Sum Root to Leaf Numbers", "difficulty": "Medium", "tags": "Tree,DFS", "companies": "Google"},
    {"title": "Surrounded Regions", "difficulty": "Medium", "tags": "BFS/DFS,Graph", "companies": "Google"},
    {"title": "Palindrome Partitioning", "difficulty": "Medium", "tags": "Backtracking,Dynamic Programming", "companies": "Google,Amazon"},
    {"title": "Palindrome Partitioning II", "difficulty": "Hard", "tags": "Dynamic Programming", "companies": "Google"},
    {"title": "Clone Graph", "difficulty": "Medium", "tags": "Graph,BFS/DFS", "companies": "Google,Meta"},
    {"title": "Gas Station", "difficulty": "Medium", "tags": "Greedy", "companies": "Google,Amazon"},
    {"title": "Candy", "difficulty": "Hard", "tags": "Greedy", "companies": "Google"},
    {"title": "Single Number", "difficulty": "Easy", "tags": "Bit Manipulation", "companies": "Google,Amazon"},
    {"title": "Single Number II", "difficulty": "Medium", "tags": "Bit Manipulation", "companies": "Google"},
    {"title": "Single Number III", "difficulty": "Medium", "tags": "Bit Manipulation", "companies": "Google"},
    {"title": "Copy List with Random Pointer", "difficulty": "Medium", "tags": "Linked List,HashMap", "companies": "Google,Amazon"},
    {"title": "Word Break", "difficulty": "Medium", "tags": "Dynamic Programming,Trie", "companies": "Google,Amazon,Meta"},
    {"title": "Word Break II", "difficulty": "Hard", "tags": "Dynamic Programming,Backtracking", "companies": "Google"},
    {"title": "Linked List Cycle", "difficulty": "Easy", "tags": "Linked List,Two Pointers", "companies": "Google,Amazon"},
    {"title": "Linked List Cycle II", "difficulty": "Medium", "tags": "Linked List,Two Pointers", "companies": "Google,Amazon"},
    {"title": "Reorder List", "difficulty": "Medium", "tags": "Linked List,Two Pointers", "companies": "Google,Amazon"},
    {"title": "Binary Tree Preorder Traversal", "difficulty": "Easy", "tags": "Tree,DFS", "companies": "Google"},
    {"title": "Binary Tree Postorder Traversal", "difficulty": "Easy", "tags": "Tree,DFS", "companies": "Google"},
    {"title": "LRU Cache", "difficulty": "Medium", "tags": "HashMap,LinkedList", "companies": "Amazon,Meta"},
    {"title": "Insertion Sort List", "difficulty": "Medium", "tags": "Linked List,Sorting", "companies": "Google"},
    {"title": "Sort List", "difficulty": "Medium", "tags": "Linked List,Merge Sort", "companies": "Google,Amazon"},
    {"title": "Max Points on a Line", "difficulty": "Hard", "tags": "Math,HashMap", "companies": "Google"},
    {"title": "Evaluate Reverse Polish Notation", "difficulty": "Medium", "tags": "Stack,Math", "companies": "Google,Amazon"},
    {"title": "Reverse Words in a String", "difficulty": "Medium", "tags": "String,Two Pointers", "companies": "Google,Amazon"},
    {"title": "Maximum Product Subarray", "difficulty": "Medium", "tags": "Dynamic Programming", "companies": "Google,Amazon"},
    {"title": "Find Minimum in Rotated Sorted Array", "difficulty": "Medium", "tags": "Binary Search", "companies": "Google,Amazon"},
    {"title": "Find Minimum in Rotated Sorted Array II", "difficulty": "Hard", "tags": "Binary Search", "companies": "Google"},
    {"title": "Min Stack", "difficulty": "Medium", "tags": "Stack,Design", "companies": "Google,Amazon"},
    {"title": "Intersection of Two Linked Lists", "difficulty": "Easy", "tags": "Linked List,Two Pointers", "companies": "Google,Amazon"},
    {"title": "Find Peak Element", "difficulty": "Medium", "tags": "Binary Search", "companies": "Google"},
    {"title": "Maximum Gap", "difficulty": "Hard", "tags": "Sorting,Bucket Sort", "companies": "Google"},
    {"title": "Compare Version Numbers", "difficulty": "Medium", "tags": "String,Two Pointers", "companies": "Google"},
    {"title": "Fraction to Recurring Decimal", "difficulty": "Medium", "tags": "Math,HashMap", "companies": "Google"},
    {"title": "Two Sum II Input Array Is Sorted", "difficulty": "Medium", "tags": "Two Pointers,Binary Search", "companies": "Google,Amazon"},
    {"title": "Excel Sheet Column Title", "difficulty": "Easy", "tags": "Math,String", "companies": "Google"},
    {"title": "Majority Element", "difficulty": "Easy", "tags": "Array,HashMap", "companies": "Google,Amazon"},
    {"title": "Excel Sheet Column Number", "difficulty": "Easy", "tags": "Math", "companies": "Google"},
    {"title": "Factorial Trailing Zeroes", "difficulty": "Medium", "tags": "Math", "companies": "Google"},
    {"title": "Binary Search Tree Iterator", "difficulty": "Medium", "tags": "Tree,Stack,Design", "companies": "Google,Amazon"},
    {"title": "Dungeon Game", "difficulty": "Hard", "tags": "Dynamic Programming", "companies": "Google"},
    {"title": "Combine Two Tables", "difficulty": "Easy", "tags": "SQL", "companies": "Google"},
    {"title": "Largest Number", "difficulty": "Medium", "tags": "Sorting,String", "companies": "Google,Amazon"},
    {"title": "Reverse Words in a String II", "difficulty": "Medium", "tags": "String,Two Pointers", "companies": "Google"},
    {"title": "Repeated DNA Sequences", "difficulty": "Medium", "tags": "HashMap,Sliding Window", "companies": "Google"},
    {"title": "Best Time to Buy and Sell Stock IV", "difficulty": "Hard", "tags": "Dynamic Programming", "companies": "Google"},
    {"title": "Rotate Array", "difficulty": "Medium", "tags": "Array", "companies": "Google,Amazon"},
    {"title": "Reverse Bits", "difficulty": "Easy", "tags": "Bit Manipulation", "companies": "Google,Apple"},
    {"title": "Number of 1 Bits", "difficulty": "Easy", "tags": "Bit Manipulation", "companies": "Google,Apple"},
    {"title": "Word Frequency", "difficulty": "Medium", "tags": "String,HashMap", "companies": "Google"},
    {"title": "Happy Number", "difficulty": "Easy", "tags": "HashMap,Math", "companies": "Google,Amazon"},
    {"title": "Remove Linked List Elements", "difficulty": "Easy", "tags": "Linked List", "companies": "Google"},
    {"title": "Count Primes", "difficulty": "Medium", "tags": "Math,Sieve of Eratosthenes", "companies": "Google,Amazon"},
    {"title": "Isomorphic Strings", "difficulty": "Easy", "tags": "HashMap,String", "companies": "Google"},
    {"title": "Reverse Linked List", "difficulty": "Easy", "tags": "Linked List", "companies": "Google,Meta"},
    {"title": "Course Schedule", "difficulty": "Medium", "tags": "Graph,Topological Sort", "companies": "Google"},
    {"title": "Course Schedule II", "difficulty": "Medium", "tags": "Graph,Topological Sort", "companies": "Google"},
    {"title": "Implement Trie Prefix Tree", "difficulty": "Medium", "tags": "Trie,Design", "companies": "Google,Amazon,Meta"},
    {"title": "Add and Search Word Data Structure Design", "difficulty": "Medium", "tags": "Trie,DFS", "companies": "Google"},
    {"title": "Word Search II", "difficulty": "Hard", "tags": "Trie,DFS,Backtracking", "companies": "Google,Amazon"},
    {"title": "House Robber", "difficulty": "Medium", "tags": "Dynamic Programming", "companies": "Google,Amazon"},
    {"title": "House Robber II", "difficulty": "Medium", "tags": "Dynamic Programming", "companies": "Google"},
    {"title": "Shortest Palindrome", "difficulty": "Hard", "tags": "String,KMP", "companies": "Google"},
    {"title": "Kth Largest Element in an Array", "difficulty": "Medium", "tags": "Heap,QuickSelect", "companies": "Google,Amazon,Meta"},
    {"title": "Combination Sum III", "difficulty": "Medium", "tags": "Backtracking", "companies": "Google"},
    {"title": "Contains Duplicate", "difficulty": "Easy", "tags": "HashMap", "companies": "Google,Amazon"},
    {"title": "Contains Duplicate II", "difficulty": "Easy", "tags": "HashMap,Sliding Window", "companies": "Google"},
    {"title": "Contains Duplicate III", "difficulty": "Hard", "tags": "Sliding Window,Sorted Set", "companies": "Google"},
    {"title": "Maximal Square", "difficulty": "Medium", "tags": "Dynamic Programming", "companies": "Google,Amazon"},
    {"title": "Count Complete Tree Nodes", "difficulty": "Easy", "tags": "Tree,Binary Search", "companies": "Google"},
    {"title": "Rectangle Area", "difficulty": "Medium", "tags": "Math,Geometry", "companies": "Google"},
    {"title": "Basic Calculator", "difficulty": "Hard", "tags": "Stack,Math", "companies": "Google"},
    {"title": "Implement Stack using Queues", "difficulty": "Easy", "tags": "Stack,Queue,Design", "companies": "Google"},
    {"title": "Invert Binary Tree", "difficulty": "Easy", "tags": "Tree,DFS", "companies": "Google"},
    {"title": "Basic Calculator II", "difficulty": "Medium", "tags": "Stack,Math", "companies": "Google"},
    {"title": "Summary Ranges", "difficulty": "Easy", "tags": "Array,Two Pointers", "companies": "Google"},
    {"title": "Majority Element II", "difficulty": "Medium", "tags": "Array,HashMap", "companies": "Google"},
    {"title": "Kth Smallest Element in a BST", "difficulty": "Medium", "tags": "Tree,DFS", "companies": "Google,Amazon"},
    {"title": "Power of Two", "difficulty": "Easy", "tags": "Bit Manipulation,Math", "companies": "Google"},
    {"title": "Implement Queue using Stacks", "difficulty": "Easy", "tags": "Stack,Queue,Design", "companies": "Google"},
    {"title": "Number of Digit One", "difficulty": "Hard", "tags": "Math", "companies": "Google"},
    {"title": "Palindrome Linked List", "difficulty": "Easy", "tags": "Linked List,Two Pointers", "companies": "Google,Amazon"},
    {"title": "Lowest Common Ancestor of BST", "difficulty": "Medium", "tags": "Tree,DFS", "companies": "Google,Amazon"},
    {"title": "Delete Node in a Linked List", "difficulty": "Medium", "tags": "Linked List", "companies": "Google"},
    {"title": "Product of Array Except Self", "difficulty": "Medium", "tags": "Array,Prefix Sum", "companies": "Google,Amazon,Meta"},
    {"title": "Sliding Window Maximum", "difficulty": "Hard", "tags": "Sliding Window,Deque", "companies": "Google,Amazon"},
    {"title": "Search a 2D Matrix II", "difficulty": "Medium", "tags": "Binary Search,Matrix", "companies": "Google,Amazon"},
    {"title": "Different Ways to Add Parentheses", "difficulty": "Medium", "tags": "Divide and Conquer,Dynamic Programming", "companies": "Google"},
    {"title": "Valid Anagram", "difficulty": "Easy", "tags": "HashMap,String", "companies": "Google,Amazon"},
    {"title": "Shortest Word Distance", "difficulty": "Easy", "tags": "Array,String", "companies": "LinkedIn"},
    {"title": "Strobogrammatic Number", "difficulty": "Easy", "tags": "Math,String", "companies": "Google"},
    {"title": "Meeting Rooms", "difficulty": "Easy", "tags": "Sorting,Intervals", "companies": "Google,Meta"},
    {"title": "Meeting Rooms II", "difficulty": "Medium", "tags": "Heap,Intervals", "companies": "Google,Amazon,Meta"},
    {"title": "Factor Combinations", "difficulty": "Medium", "tags": "Backtracking,Math", "companies": "Google"},
    {"title": "Verify Preorder Sequence in BST", "difficulty": "Medium", "tags": "Tree,Stack", "companies": "Google"},
    {"title": "Paint House", "difficulty": "Medium", "tags": "Dynamic Programming", "companies": "Meta"},
    {"title": "Binary Tree Paths", "difficulty": "Easy", "tags": "Tree,DFS,Backtracking", "companies": "Google"},
    {"title": "Add Digits", "difficulty": "Easy", "tags": "Math", "companies": "Google"},
    {"title": "Binary Watch", "difficulty": "Easy", "tags": "Bit Manipulation,Backtracking", "companies": "Google"},
    {"title": "Find the Duplicate Number", "difficulty": "Medium", "tags": "Array,Two Pointers", "companies": "Google,Amazon"},
    {"title": "Game of Life", "difficulty": "Medium", "tags": "Array,Matrix", "companies": "Google"},
    {"title": "Word Pattern", "difficulty": "Easy", "tags": "HashMap,String", "companies": "Google"},
    {"title": "Find Median from Data Stream", "difficulty": "Hard", "tags": "Heap,Design", "companies": "Google,Amazon"},
    {"title": "Integer to English Words", "difficulty": "Hard", "tags": "Math,String,Recursion", "companies": "Google,Amazon"},
    {"title": "H-Index", "difficulty": "Medium", "tags": "Sorting,Binary Search", "companies": "Google"},
    {"title": "H-Index II", "difficulty": "Medium", "tags": "Binary Search", "companies": "Google"},
    {"title": "Paint House II", "difficulty": "Hard", "tags": "Dynamic Programming", "companies": "Meta"},
    {"title": "Graph Valid Tree", "difficulty": "Medium", "tags": "Graph,Union Find", "companies": "Google,LinkedIn"},
    {"title": "Number of Connected Components in Undirected Graph", "difficulty": "Medium", "tags": "Graph,Union Find", "companies": "Google,LinkedIn"},
    {"title": "Alien Dictionary", "difficulty": "Hard", "tags": "Graph,Topological Sort", "companies": "Google,Meta"},
    {"title": "Closest Binary Search Tree Value", "difficulty": "Easy", "tags": "Tree,Binary Search", "companies": "Google"},
    {"title": "Encode and Decode Strings", "difficulty": "Medium", "tags": "String,Design", "companies": "Google"},
    {"title": "Find the Celebrity", "difficulty": "Medium", "tags": "Graph,Two Pointers", "companies": "Google"},
    {"title": "Wiggle Sort", "difficulty": "Medium", "tags": "Array,Greedy", "companies": "Google"},
    {"title": "Rearrange String k Distance Apart", "difficulty": "Hard", "tags": "Heap,Greedy", "companies": "Google"},
    {"title": "Palindrome Permutation", "difficulty": "Easy", "tags": "HashMap,String", "companies": "Google"},
    {"title": "Palindrome Permutation II", "difficulty": "Medium", "tags": "Backtracking,String", "companies": "Google"},
    {"title": "Zigzag Iterator", "difficulty": "Medium", "tags": "Array,Design", "companies": "Google"},
    {"title": "Unique Word Abbreviation", "difficulty": "Medium", "tags": "HashMap,String", "companies": "Google"},
    {"title": "Lowest Common Ancestor of Binary Tree", "difficulty": "Medium", "tags": "Tree,DFS", "companies": "Google,Amazon,Meta"},
    {"title": "Product of Array Except Self", "difficulty": "Medium", "tags": "Array", "companies": "Google,Amazon"},
    {"title": "Two Sum III Data Structure Design", "difficulty": "Easy", "tags": "HashMap,Design", "companies": "LinkedIn"},
    {"title": "Largest BST Subtree", "difficulty": "Medium", "tags": "Tree,DFS", "companies": "Google"},
    {"title": "Best Meeting Point", "difficulty": "Hard", "tags": "Math,Sorting", "companies": "Google"},
    {"title": "Expression Add Operators", "difficulty": "Hard", "tags": "Backtracking,Math", "companies": "Google"},
    {"title": "Move Zeroes", "difficulty": "Easy", "tags": "Array,Two Pointers", "companies": "Google,Meta"},
    {"title": "Peeking Iterator", "difficulty": "Medium", "tags": "Design,Iterator", "companies": "Google"},
    {"title": "Find the Duplicate Number", "difficulty": "Medium", "tags": "Array", "companies": "Google"},
    {"title": "Game of Life", "difficulty": "Medium", "tags": "Array,Matrix", "companies": "Google"},
    {"title": "Word Pattern", "difficulty": "Easy", "tags": "String,HashMap", "companies": "Google"},
    {"title": "Nim Game", "difficulty": "Easy", "tags": "Math,Game Theory", "companies": "Google"},
    {"title": "Flip Game", "difficulty": "Easy", "tags": "String,Game Theory", "companies": "Google"},
    {"title": "Bulls and Cows", "difficulty": "Medium", "tags": "HashMap,String", "companies": "Google"},
    {"title": "Longest Increasing Subsequence", "difficulty": "Medium", "tags": "Dynamic Programming,Binary Search", "companies": "Google,Amazon"},
    {"title": "Remove Invalid Parentheses", "difficulty": "Hard", "tags": "BFS,Backtracking", "companies": "Meta"},
    {"title": "Smallest Rectangle Enclosing Black Pixels", "difficulty": "Hard", "tags": "Binary Search,DFS", "companies": "Google"},
    {"title": "Perfect Squares", "difficulty": "Medium", "tags": "Dynamic Programming,BFS", "companies": "Google"},
    {"title": "Wiggle Sort II", "difficulty": "Medium", "tags": "Array,Sorting", "companies": "Google"},
    {"title": "Find the Celebrity", "difficulty": "Medium", "tags": "Graph", "companies": "Google"},
    {"title": "Range Sum Query Immutable", "difficulty": "Easy", "tags": "Prefix Sum,Design", "companies": "Google"},
    {"title": "Range Sum Query 2D Immutable", "difficulty": "Medium", "tags": "Prefix Sum,Matrix", "companies": "Google"},
    {"title": "Number of Islands", "difficulty": "Medium", "tags": "BFS/DFS,Graph", "companies": "Google,Amazon"},
    {"title": "Walls and Gates", "difficulty": "Medium", "tags": "BFS,Graph", "companies": "Google"},
    {"title": "Longest Increasing Path in a Matrix", "difficulty": "Hard", "tags": "DFS,Dynamic Programming", "companies": "Google"},
    {"title": "Coins in a Line", "difficulty": "Medium", "tags": "Dynamic Programming,Game Theory", "companies": "Google"},
    {"title": "Alien Dictionary", "difficulty": "Hard", "tags": "Topological Sort,Graph", "companies": "Google,Meta"},
    {"title": "Serialize and Deserialize Binary Tree", "difficulty": "Hard", "tags": "Tree,BFS,Design", "companies": "Google,Meta"},
    {"title": "Smallest Good Base", "difficulty": "Hard", "tags": "Math,Binary Search", "companies": "Google"},
    {"title": "Reconstruct Itinerary", "difficulty": "Hard", "tags": "Graph,DFS,Euler Path", "companies": "Google"},
    {"title": "Increasing Triplet Subsequence", "difficulty": "Medium", "tags": "Array,Greedy", "companies": "Google,Amazon"},
    {"title": "Self Crossing", "difficulty": "Hard", "tags": "Math,Geometry", "companies": "Google"},
    {"title": "Palindrome Pairs", "difficulty": "Hard", "tags": "HashMap,Trie", "companies": "Google,Airbnb"},
    {"title": "House Robber III", "difficulty": "Medium", "tags": "Tree,Dynamic Programming", "companies": "Google"},
    {"title": "Counting Bits", "difficulty": "Easy", "tags": "Bit Manipulation,Dynamic Programming", "companies": "Google"},
    {"title": "Nested List Weight Sum", "difficulty": "Medium", "tags": "DFS,BFS", "companies": "Google,LinkedIn"},
    {"title": "Flat Nested List Iterator", "difficulty": "Medium", "tags": "Stack,Design,Iterator", "companies": "Google"},
    {"title": "Reverse String", "difficulty": "Easy", "tags": "String,Two Pointers", "companies": "Google"},
    {"title": "Reverse Vowels of a String", "difficulty": "Easy", "tags": "String,Two Pointers", "companies": "Google"},
    {"title": "Moving Average from Data Stream", "difficulty": "Easy", "tags": "Queue,Design", "companies": "Google"},
    {"title": "Intersection of Two Arrays", "difficulty": "Easy", "tags": "HashMap,Binary Search", "companies": "Google"},
    {"title": "Intersection of Two Arrays II", "difficulty": "Easy", "tags": "HashMap,Binary Search", "companies": "Google"},
    {"title": "Android Unlock Patterns", "difficulty": "Medium", "tags": "Backtracking,DFS", "companies": "Google"},
    {"title": "Top K Frequent Elements", "difficulty": "Medium", "tags": "Heap,HashMap", "companies": "Google,Amazon,Meta"},
    {"title": "Data Stream as Disjoint Intervals", "difficulty": "Hard", "tags": "Sorted Set,Design", "companies": "Google"},
    {"title": "Find K Pairs with Smallest Sums", "difficulty": "Medium", "tags": "Heap", "companies": "Google"},
    {"title": "Guess Number Higher or Lower", "difficulty": "Easy", "tags": "Binary Search,Interactive", "companies": "Google"},
    {"title": "Wiggle Subsequence", "difficulty": "Medium", "tags": "Greedy,Dynamic Programming", "companies": "Google"},
    {"title": "Combination Sum IV", "difficulty": "Medium", "tags": "Dynamic Programming", "companies": "Google"},
    {"title": "Kth Smallest Element in a Sorted Matrix", "difficulty": "Medium", "tags": "Heap,Binary Search", "companies": "Google"},
    {"title": "Design Twitter", "difficulty": "Medium", "tags": "Heap,HashMap,OOP,Design", "companies": "Google"},
    {"title": "Decode String", "difficulty": "Medium", "tags": "Stack,String", "companies": "Google,Amazon"},
    {"title": "Longest Substring with At Least K Repeating Characters", "difficulty": "Medium", "tags": "Sliding Window,Divide and Conquer", "companies": "Google"},
    {"title": "Rotate Function", "difficulty": "Medium", "tags": "Math,Dynamic Programming", "companies": "Google"},
    {"title": "Integer Replacement", "difficulty": "Medium", "tags": "Bit Manipulation,Math", "companies": "Google"},
    {"title": "Random Pick Index", "difficulty": "Medium", "tags": "Reservoir Sampling,Math", "companies": "Google"},
    {"title": "Evaluate Division", "difficulty": "Medium", "tags": "Graph,BFS,Union Find", "companies": "Google"},
    {"title": "Nth Digit", "difficulty": "Medium", "tags": "Math,Binary Search", "companies": "Google"},
    {"title": "Remove K Digits", "difficulty": "Medium", "tags": "Stack,Greedy,Monotonic Stack", "companies": "Google"},
    {"title": "Frog Jump", "difficulty": "Hard", "tags": "Dynamic Programming,Graph", "companies": "Google"},
    {"title": "Sum of Left Leaves", "difficulty": "Easy", "tags": "Tree,DFS", "companies": "Google"},
    {"title": "Convert a Number to Hexadecimal", "difficulty": "Easy", "tags": "Bit Manipulation,Math", "companies": "Google"},
    {"title": "Queue Reconstruction by Height", "difficulty": "Medium", "tags": "Greedy,Sorting", "companies": "Google"},
    {"title": "Trapping Rain Water II", "difficulty": "Hard", "tags": "Heap,BFS,Matrix", "companies": "Google"},
    {"title": "Valid Perfect Square", "difficulty": "Easy", "tags": "Math,Binary Search", "companies": "Google"},
    {"title": "Sum of Two Integers", "difficulty": "Medium", "tags": "Bit Manipulation", "companies": "Google,Amazon"},
    {"title": "Find All Numbers Disappeared in an Array", "difficulty": "Easy", "tags": "Array,HashMap", "companies": "Google"},
    {"title": "Serialize and Deserialize BST", "difficulty": "Medium", "tags": "Tree,DFS", "companies": "Google"},
    {"title": "Delete Node in a BST", "difficulty": "Medium", "tags": "Tree,DFS", "companies": "Google"},
    {"title": "Number of Segments in a String", "difficulty": "Easy", "tags": "String", "companies": "Google"},
    {"title": "Non-overlapping Intervals", "difficulty": "Medium", "tags": "Greedy,Intervals", "companies": "Google"},
    {"title": "Find Right Interval", "difficulty": "Medium", "tags": "Binary Search,Sorting", "companies": "Google"},
    {"title": "Path Sum III", "difficulty": "Medium", "tags": "Tree,DFS,Prefix Sum", "companies": "Google"},
    {"title": "Find All Duplicates in an Array", "difficulty": "Medium", "tags": "Array,HashMap", "companies": "Google"},
    {"title": "String Compression", "difficulty": "Medium", "tags": "String,Two Pointers", "companies": "Google"},
    {"title": "Add Two Numbers II", "difficulty": "Medium", "tags": "Linked List,Stack", "companies": "Google"},
    {"title": "Number of Boomerangs", "difficulty": "Medium", "tags": "HashMap,Math", "companies": "Google"},
    {"title": "Find All Anagrams in a String", "difficulty": "Medium", "tags": "HashMap,Sliding Window", "companies": "Google"},
    {"title": "Ternary Expression Parser", "difficulty": "Medium", "tags": "Stack,String,DFS", "companies": "Google"},
    {"title": "Arranging Coins", "difficulty": "Easy", "tags": "Math,Binary Search", "companies": "Google"},
    {"title": "Find Duplicate File in System", "difficulty": "Medium", "tags": "HashMap,String", "companies": "Google,Dropbox"},
    {"title": "Construct the Rectangle", "difficulty": "Easy", "tags": "Math", "companies": "Google"},
    {"title": "Reverse String II", "difficulty": "Easy", "tags": "String,Two Pointers", "companies": "Google"},
    {"title": "Student Attendance Record I", "difficulty": "Easy", "tags": "String", "companies": "Google"},
    {"title": "Reverse Words in a String III", "difficulty": "Easy", "tags": "String,Two Pointers", "companies": "Google"},
    {"title": "Array Partition I", "difficulty": "Easy", "tags": "Array,Greedy,Sorting", "companies": "Google"},
    {"title": "Fibonacci Number", "difficulty": "Easy", "tags": "Dynamic Programming,Recursion", "companies": "Google,Amazon"},
    {"title": "Is Subsequence", "difficulty": "Easy", "tags": "String,Two Pointers,Dynamic Programming", "companies": "Google"},
    {"title": "Number of Steps to Reduce Number to Zero", "difficulty": "Easy", "tags": "Bit Manipulation,Math", "companies": "Google"},
    {"title": "Maximum Number of Vowels in Substring", "difficulty": "Medium", "tags": "Sliding Window,String", "companies": "Google"},
    {"title": "Max Consecutive Ones III", "difficulty": "Medium", "tags": "Sliding Window,Binary Search", "companies": "Google"},
    {"title": "Subarray Product Less Than K", "difficulty": "Medium", "tags": "Sliding Window,Array", "companies": "Google"},
    {"title": "Maximum Average Subarray I", "difficulty": "Easy", "tags": "Sliding Window,Array", "companies": "Google"},
    {"title": "Diet Plan Performance", "difficulty": "Easy", "tags": "Sliding Window,Array", "companies": "Google"},
    {"title": "Number of Sub-arrays of Size K and Average", "difficulty": "Medium", "tags": "Sliding Window,Array", "companies": "Google"},
    {"title": "Minimum Size Subarray Sum", "difficulty": "Medium", "tags": "Sliding Window,Two Pointers", "companies": "Google,Amazon"},
    {"title": "Fruit Into Baskets", "difficulty": "Medium", "tags": "Sliding Window,HashMap", "companies": "Google"},
    {"title": "Longest Repeating Character Replacement", "difficulty": "Medium", "tags": "Sliding Window,HashMap", "companies": "Google"},
    {"title": "Permutation in String", "difficulty": "Medium", "tags": "Sliding Window,HashMap", "companies": "Google"},
    {"title": "Check Inclusion", "difficulty": "Medium", "tags": "Sliding Window,HashMap", "companies": "Google"},
    {"title": "Grumpy Bookstore Owner", "difficulty": "Medium", "tags": "Sliding Window,Array", "companies": "Google"},
    {"title": "Get Equal Substrings Within Budget", "difficulty": "Medium", "tags": "Sliding Window,Array", "companies": "Google"},
    {"title": "Longest Continuous Subarray With Absolute Diff", "difficulty": "Medium", "tags": "Sliding Window,Monotonic Deque", "companies": "Google"},
    {"title": "Max Value of Equation", "difficulty": "Hard", "tags": "Sliding Window,Monotonic Deque", "companies": "Google"},
    {"title": "Minimum Operations to Reduce X to Zero", "difficulty": "Medium", "tags": "Sliding Window,Prefix Sum", "companies": "Google"},
    {"title": "K Radius Subarray Averages", "difficulty": "Medium", "tags": "Sliding Window,Array", "companies": "Google"},
    {"title": "Find the Longest Substring Containing Vowels", "difficulty": "Medium", "tags": "Sliding Window,Bit Manipulation", "companies": "Google"},
    {"title": "Minimum Swaps to Group All 1s Together", "difficulty": "Medium", "tags": "Sliding Window,Array", "companies": "Google"},
    {"title": "Maximum Points You Can Obtain from Cards", "difficulty": "Medium", "tags": "Sliding Window,Array,Prefix Sum", "companies": "Google"},
    {"title": "Maximum Erasure Value", "difficulty": "Medium", "tags": "Sliding Window,HashMap", "companies": "Google"},
    {"title": "Count Number of Nice Subarrays", "difficulty": "Medium", "tags": "Sliding Window,Prefix Sum", "companies": "Google"},
    {"title": "Replace the Substring for Balanced String", "difficulty": "Medium", "tags": "Sliding Window,HashMap", "companies": "Google"},
    {"title": "Number of Substrings Containing All Three Characters", "difficulty": "Medium", "tags": "Sliding Window,HashMap", "companies": "Google"},
    {"title": "Binary Subarrays With Sum", "difficulty": "Medium", "tags": "Sliding Window,Prefix Sum,HashMap", "companies": "Google"},
    {"title": "Subarrays with K Different Integers", "difficulty": "Hard", "tags": "Sliding Window,HashMap", "companies": "Google"},
    {"title": "Shortest Subarray with Sum at Least K", "difficulty": "Hard", "tags": "Sliding Window,Monotonic Deque", "companies": "Google"},
    {"title": "Number of Ways to Split a String", "difficulty": "Medium", "tags": "Math,String", "companies": "Google"},
    {"title": "Maximum Number of Non-Overlapping Subarrays With Sum Equals Target", "difficulty": "Medium", "tags": "Greedy,HashMap,Prefix Sum", "companies": "Google"},
    {"title": "K Closest Points to Origin", "difficulty": "Medium", "tags": "Heap,Math,QuickSelect", "companies": "Google,Amazon"},
    {"title": "Reorganize String", "difficulty": "Medium", "tags": "Heap,Greedy,HashMap", "companies": "Google"},
    {"title": "Task Scheduler", "difficulty": "Medium", "tags": "Heap,Greedy,HashMap", "companies": "Google,Amazon"},
    {"title": "Minimum Cost to Connect Sticks", "difficulty": "Medium", "tags": "Heap,Greedy", "companies": "Google,Amazon"},
    {"title": "Find K-th Smallest Pair Distance", "difficulty": "Hard", "tags": "Binary Search,Two Pointers,Sorting", "companies": "Google"},
    {"title": "Swim in Rising Water", "difficulty": "Hard", "tags": "Heap,Binary Search,DFS,Union Find", "companies": "Google"},
    {"title": "Minimum Cost to Hire K Workers", "difficulty": "Hard", "tags": "Heap,Greedy,Sorting", "companies": "Google"},
    {"title": "IPO", "difficulty": "Hard", "tags": "Heap,Greedy,Sorting", "companies": "Google"},
    {"title": "Find Median from Data Stream", "difficulty": "Hard", "tags": "Heap,Design,Two Pointers", "companies": "Google,Amazon"},
    {"title": "Sliding Window Median", "difficulty": "Hard", "tags": "Heap,Sliding Window", "companies": "Google"},
    {"title": "Maximum Performance of a Team", "difficulty": "Hard", "tags": "Heap,Greedy,Sorting", "companies": "Google"},
    {"title": "The Skyline Problem", "difficulty": "Hard", "tags": "Heap,Divide and Conquer,Segment Tree", "companies": "Google"},
    {"title": "Distant Barcodes", "difficulty": "Medium", "tags": "Heap,Greedy,HashMap", "companies": "Google"},
    {"title": "Furthest Building You Can Reach", "difficulty": "Medium", "tags": "Heap,Greedy", "companies": "Google"},
    {"title": "Find the Most Competitive Subsequence", "difficulty": "Medium", "tags": "Heap,Stack,Greedy", "companies": "Google"},
    {"title": "Minimum Number of Refueling Stops", "difficulty": "Hard", "tags": "Heap,Dynamic Programming,Greedy", "companies": "Google"},
    {"title": "Campus Bikes", "difficulty": "Medium", "tags": "Heap,Greedy,Sorting", "companies": "Google"},
    {"title": "Car Pooling", "difficulty": "Medium", "tags": "Heap,Sorting,Greedy", "companies": "Google"},
    {"title": "Single-Threaded CPU", "difficulty": "Medium", "tags": "Heap,Sorting,Simulation", "companies": "Google"},
    {"title": "Process Tasks Using Servers", "difficulty": "Medium", "tags": "Heap,Simulation", "companies": "Google"},
    {"title": "Minimum Interval to Include Each Query", "difficulty": "Hard", "tags": "Heap,Sorting,Binary Search", "companies": "Google"},
    {"title": "Network Delay Time", "difficulty": "Medium", "tags": "Graph,Dijkstra,Heap", "companies": "Google,Amazon"},
    {"title": "Cheapest Flights Within K Stops", "difficulty": "Medium", "tags": "Graph,Dijkstra,Bellman-Ford,BFS", "companies": "Google"},
    {"title": "Path with Maximum Probability", "difficulty": "Medium", "tags": "Graph,Dijkstra,Heap", "companies": "Google"},
    {"title": "Find the City With the Smallest Number of Neighbors", "difficulty": "Medium", "tags": "Graph,Shortest Path,Dynamic Programming", "companies": "Google"},
    {"title": "Minimum Cost to Make at Least One Valid Path in a Grid", "difficulty": "Hard", "tags": "Graph,BFS,Dijkstra", "companies": "Google"},
    {"title": "Reachable Nodes In Subdivided Graph", "difficulty": "Hard", "tags": "Graph,Dijkstra,Heap", "companies": "Google"},
    {"title": "Minimum Weighted Subgraph With the Required Paths", "difficulty": "Hard", "tags": "Graph,Dijkstra", "companies": "Google"},
    {"title": "Maximum Total Importance of Roads", "difficulty": "Medium", "tags": "Graph,Greedy,Sorting", "companies": "Google"},
    {"title": "Count Unreachable Pairs of Nodes in an Undirected Graph", "difficulty": "Medium", "tags": "Graph,Union Find,DFS", "companies": "Google"},
    {"title": "Number of Ways to Arrive at Destination", "difficulty": "Medium", "tags": "Graph,Dijkstra,Dynamic Programming", "companies": "Google"},
    {"title": "All Pairs Shortest Path", "difficulty": "Medium", "tags": "Graph,Floyd-Warshall,Dynamic Programming", "companies": "Google"},
]

# Connect to ChromaDB
client = chromadb.PersistentClient(path="./chroma_db")

# Delete old collection
try:
    client.delete_collection("leetcode")
    print("🗑️ Deleted old collection")
except:
    pass

# Create fresh collection
collection = client.create_collection("leetcode")
model = SentenceTransformer("all-MiniLM-L6-v2")

print(f"📚 Adding {len(problems)} problems...")

for i, p in enumerate(problems):
    embedding = model.encode(p["title"]).tolist()
    collection.add(
        ids=[str(i)],
        embeddings=[embedding],
        metadatas=[p]
    )
    print(f"✅ [{i+1}/{len(problems)}] {p['title']}")

print(f"\n🎉 Done! Added {len(problems)} problems!")
